// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./src/components/CommonHeader.vue')['default'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElEmpty: typeof import('element-plus/es')['ElEmpty'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElLink: typeof import('element-plus/es')['ElLink'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElTag: typeof import('element-plus/es')['ElTag'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    FixedWidget: typeof import('./src/components/FixedWidget.vue')['default'];
    Github: typeof import('./src/components/svg/Github.vue')['default'];
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    Loading: typeof import('element-plus/es')['ElLoadingDirective'];
    Pie: typeof import('./src/components/Pie.vue')['default'];
    Question: typeof import('./src/components/Question.vue')['default'];
    QuestionDifficulty: typeof import('./src/components/QuestionDifficulty.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    RuleAlert: typeof import('./src/components/RuleAlert.vue')['default'];
  }
}

export {};
